-- plugins/lazygit.lua
-- kdheepak/lazygit.nvim is a Vimscript plugin; it registers :LazyGit/:LazyGitConfig
-- commands automatically. There is no Lua setup() function to call.
-- Keymaps are defined in core/keymaps.lua (<leader>gg).
